FROM: Anshum <ansh...@gmail.com>
SUBJECT: Re: LockObtainFailedException
DATE: 2 Nov 2009

Hi Chris,

Isn't there a reply @ the older thread?
In case there isn't, this is generally observed when an indexwriter is not
closed properly i.e. just not closed.
The lock is created on opening the indexwriter to maintain the sanity of the
index. This lock gets removed on closing writer.close(). In case of
exceptions, when the indexwriter.close() is not closed, the subsequent call
to an index operation (opening a writer) would result in a
lockobtainfailedexception.
Try using a finally block to handle such cases.

--
Anshum Gupta
Naukri Labs!
http://ai-cafe.blogspot.com

The facts expressed here belong to everybody, the opinions to me. The
distinction is yours to draw............


On Mon, Nov 2, 2009 at 3:27 PM, Chris Bamford <Chris.Bamford@scalix.com>wrote:

> Hi,
>
> I was researching LockObtainFailedExceptions and came across this thread.
> I
> don't use Solr, just regular Lucene deployed via Tomcat - but I have
> started getting these exceptions which coincides with our recent
> upgrade from 2.0.0 to 2.4.0.
> I have found that just removing the lock file
> seems to clear up the problem, but I was hoping for (a) a better
> understanding of why they might occur in the first place and (b) some
> thoughts on how I might deal with them programatically.
>
> Thanks for any ideas / pointers,
>
> - Chris
>

