FROM: "Mindaugas Žakšauskas" <min...@gmail.com>
SUBJECT: Re: Lucene Search Error: Java.io.IOException: Bad file descriptor
DATE: 23 Jul 2008

On Wed, Jul 23, 2008 at 5:46 PM, Matthew Hall <mhall@informatics.jax.org> wrote:
> <..>As for the jave 1.6 lucene 2.3.2 index corruption issue <..>

Correct me if I'm wrong, but doesnt' the particular Sun bug [1] only
manifests itself if -Xbatch option is used? Also, the exceptions
mentioned in LUCENE-1282 does not really match the one given below:

>>>> 18007414-java.io.IOException: Bad file descriptor
>>>> 18007455-       at java.io.RandomAccessFile.seek(Native Method)

Back on topic - we're having similar (intermittant) problems on one of
our product installations, running Lucene 2.2.0. The stack trace looks
very similar with the exception of the top line which is

java.io.IOException: Bad file number
        at java.io.RandomAccessFile.seek(Native Method)
        at org.apache.lucene.store.FSDirectory$FSIndexInput.readInternal(FSDirectory.java:545)

Quick googling gave me a hint that I could be using a searcher which
appears to be closed (later I found a theoretical possibility for this
to happen in my app). I have unsuccessfully tried to reproduce this
particular exception in my dev environment so had to write this off to
multi-threading when the reader is closed just before
RandomAccessFile.seek(). I still don't know if I was right.

Jamie, is your case always reproducible, or is it somewhat random?

m.

[1] http://bugs.sun.com/bugdatabase/view_bug.do?bug_id=6707044

---------------------------------------------------------------------
To unsubscribe, e-mail: java-user-unsubscribe@lucene.apache.org
For additional commands, e-mail: java-user-help@lucene.apache.org


