FROM: Michael McCandless <luc...@mikemccandless.com>
SUBJECT: Re: IO exception during merge/optimize
DATE: 25 Oct 2009

Hmm... Lucene tries to catch the original cause (from the BG thread
doing the merge) and forward it to the main thread waiting for
optimize to complete.

Did you get any traceback printed at all?  It should include one
traceback into Lucene's optimized method, and then another (under
"caused by") showing the exception from the BG merge thread.

Did you see any BG thread exceptions on wherever your System.err is directed to?

Mike

On Sat, Oct 24, 2009 at 5:21 PM, Peter Keegan <peterlkeegan@gmail.com> wrote:
> btw, this is with Lucene 2.9
>
> On Sat, Oct 24, 2009 at 5:20 PM, Peter Keegan <peterlkeegan@gmail.com>wrote:
>
>> I'm sometimes seeing the following exception from an operation that does a
>> merge and optimize:
>> Â java.io.IOException: background merge hit exception: _0:C1082866 _1:C79
>> into _2 [optimize] [mergeDocStores]
>> I'm pretty sure that it's caused by a temporary low disk space condition,
>> but I'd like to be able to confirm this. It would be nice to have the java
>> exception included in the Lucene exception. Any way to get this?
>>
>> Peter
>>
>>
>

---------------------------------------------------------------------
To unsubscribe, e-mail: java-user-unsubscribe@lucene.apache.org
For additional commands, e-mail: java-user-help@lucene.apache.org


