FROM: "Luis Medina" <lmed...@ruralsource.com>
SUBJECT: IOException: No such path or directory
DATE: 14 Apr 2005

Hi Everyone,

The company I work for uses Lucene search 2 of their sites. Each site's
configuration is (almost) an mirror image of the other. The only difference
here is the content. We use a servlet to start up a Lucene mantainance
utility that keeps the indexes up to date. This servlet is set to load when
the servers are rebooted (which happens periodically). That way (ideally)
the mantainance util is started automatically.
I don't know if the information above is relevant to the problem, but I
thought I'd give it to you anyway, just in case.
Yesterday, I started seeing an ArrayIndexOutOfBounds exception in the logs.
I don't have the stack trace, but it is similar (almost identical, in fact)
to the stack trace found here:
http://issues.apache.org/bugzilla/show_bug.cgi?id=14355

Thinking maybe one of the indexes was corrupted, I decided to rebuild the
indexes from scratch: I stoped the mantainance utility, I deleted the
indexes, restarted the mantainance utility and let it rebuild the indexes.
This created another problem: the following exception showed up in the logs:

java.io.IOException: No such path or directory.
/.../.../.../lucenesearch/_v.fnm
      java/lang/Throwable.<init>(Ljava/lang/String;)V+4 (Throwable.java:94)
      java/lang/Exception.<init>(Ljava/lang/String;)V+1 (Exception.java:42)
      java/io/IOException.<init>(Ljava/lang/String;)V+1
(IOException.java:47)
      java/io/RandomAccessFile.<init>(Ljava/lang/String;Ljava/lang/String;)V
+0 (RandomAccessFile.java:88)
      java/io/RandomAccessFile.<init>(Ljava/io/File;Ljava/lang/String;)V+0
(RandomAccessFile.java:145)
      org/apache/lucene/store/FSInputStream$Descriptor.<init>(Lorg/apache/lu
cene/store/FSInputStream;Ljava/io/File;Ljava/lang/String;)V+0 (:??)
      org/apache/lucene/store/FSInputStream.<init>(Ljava/io/File;)V+0 (:??)
      org/apache/lucene/store/FSDirectory.openFile(Ljava/lang/String;)Lorg/a
pache/lucene/store/InputStream;+0 (:??)
      org/apache/lucene/index/FieldInfos.<init>(Lorg/apache/lucene/store/Dir
ectory;Ljava/lang/String;)V+0 (:??)
      org/apache/lucene/index/SegmentReader.<init>(Lorg/apache/lucene/index/
SegmentInfo;)V+0 (:??)
      org/apache/lucene/index/IndexWriter.mergeSegments(I)V+0 (:??)
      org/apache/lucene/index/IndexWriter.optimize()V+0 (:??)
      .../.../lucene/wc/update/LuceneUpdate.buildIndex(Ljava/lang/String;)V+
0 (:??)
      .../.../lucene/wc/update/LuceneUpdate.maintainIndex()V+0 (:??)
      .../.../lucene/wc/update/LuceneUpdate.run()V+0 (:??)
      java/lang/Thread.run()V+11 (Thread.java:479)

Some index files are generated but then the program quits and this exception
shows up in the logs over, and over and over and over and over......., along
with other exceptions, primarily reporting lock issues (except no lock files
were found in the directory).  I finally had to stop the program, delete the
files and restart it. Only that time, it actually worked.
So far, the program seems to be working, but I would like to know what
caused this problem, and if it is going to show up again. This problem
started showing up after last week's reboot, maybe it had to do with it? Has
anyone encountered anything similar before? Any suggestions?

I appreciate your help.
Thank you,

Luis A. Medina


---------------------------------------------------------------------
To unsubscribe, e-mail: java-user-unsubscribe@lucene.apache.org
For additional commands, e-mail: java-user-help@lucene.apache.org


