FROM: "Flavio Eduardo de Cordova" <flavio.cord...@datasul.com.br>
SUBJECT: IOException while searching in a new index.
DATE: 6 May 2005

Hi..

	I just updated Lucene to 1.4.3 (final) and while running some unit tests (on my application
that runs on top of lucene engine) I got the IOException: The system cannot find the path
specified.

	I found at http://java2.5341.com/msg/65116.html that there was an issue about temp directory
but I couldn't realize if it was related to the problem I'm facing now, even because it reported
a bug of RC3.

	What my unit test does: 
		1 - It creates 100 documents in a new index, closing the IndexWriter - OK !
		2 - Check it all the documents were property created by counting the documents (not searching)
- OK !
		3 - searches a subset based on one of the fields - ERROR !!!
	
	Does anybody have a clue of what's happening ? Is it really a bug or am I doing something
wrong ? If it's a bug, is there any workaround ?

	Thanks !

Fl√°vio

